spring.application.name=api

spring.datasource.url=jdbc:sqlite:finance.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mfWbxrg4TASs93t1q83ePnfiLREk7L1a2P0F2aBBv9L
jwt.expiration=86400000
